import React from "react";
import { motion } from "motion/react";
import { 
  BookOpen, 
  Compass, 
  GitBranch, 
  Archive, 
  Sparkles, 
  Download, 
  Layout, 
  User, 
  Settings,
  AlertCircle,
  Loader2
} from "lucide-react";
import { useTranslation } from "../lib/i18n";

interface GuestLockerProps {
  tab: string;
  onSignIn: () => void;
  isSigningIn: boolean;
  signInError?: string;
}

export default function GuestLocker({ tab, onSignIn, isSigningIn, signInError }: GuestLockerProps) {
  const { locale } = useTranslation();

  // Map tabs to content details
  const getTabMeta = () => {
    switch (tab) {
      case "journal":
        return {
          title: locale === "en" ? "Studio Journal" : "Diário de Ateliê",
          desc: locale === "en" 
            ? "Document your daily studio practice, material experiments, and conceptual developments freely in a quiet, distraction-free environment."
            : "Documente o seu fazer diário de ateliê, experimentos materiais e desdobramentos conceituais livremente em um ambiente silencioso e livre de distrações.",
          icon: <BookOpen className="w-8 h-8 text-stone-700 stroke-[1.2]" />
        };
      case "lab":
        return {
          title: locale === "en" ? "Seed Lab" : "Laboratório de Sementes",
          desc: locale === "en"
            ? "Seed, cultivate, and deepen your core thematic and poetic questions. Structure concepts and build connections to guide your practice."
            : "Semeie, cultive e aprofunde perguntas temáticas e poéticas fundamentais. Estruture conceitos e construa conexões para guiar seu fazer artístico.",
          icon: <Compass className="w-8 h-8 text-stone-700 stroke-[1.2]" />
        };
      case "map":
        return {
          title: locale === "en" ? "Poetic Constellation" : "Constelação Poética",
          desc: locale === "en"
            ? "Trace critical, semantic, and associative paths between sowed ideas. Visualize your entire research landscape in a fluid conceptual map."
            : "Trace caminhos críticos, semânticos e associativos entre suas ideias. Visualize todo o panorama da sua pesquisa em um mapa conceitual fluido.",
          icon: <GitBranch className="w-8 h-8 text-stone-700 stroke-[1.2]" />
        };
      case "timeline":
        return {
          title: locale === "en" ? "Timeline" : "Linha do Tempo",
          desc: locale === "en"
            ? "Observe the chronological iteration and evolution of your studio logs. Track how material experiments and concepts develop over time."
            : "Observe a evolução cronológica de seus experimentos e registros de ateliê. Acompanhe como materiais e conceitos se transformam no tempo.",
          icon: <Archive className="w-8 h-8 text-stone-700 stroke-[1.2]" />
        };
      case "insights":
        return {
          title: locale === "en" ? "Insights & Synthesis" : "Insights & Sínteses",
          desc: locale === "en"
            ? "Uncover latent patterns across your logs and receive critical, theoretical provocations generated by custom AI models aligned with your practice."
            : "Identifique padrões latentes em seus registros e receba provocações teóricas e críticas geradas por modelos de IA alinhados com sua prática.",
          icon: <Sparkles className="w-8 h-8 text-stone-700 stroke-[1.2]" />
        };
      case "export":
        return {
          title: locale === "en" ? "Export Notebook" : "Exportar Caderno",
          desc: locale === "en"
            ? "Download and export your entire research workspace, journals, and conceptual maps in clean formats for archiving, cataloging, or editing."
            : "Baixe e exporte todo o seu espaço de pesquisa, diários e mapas conceituais em formatos limpos para arquivamento, catalogação ou edição.",
          icon: <Download className="w-8 h-8 text-stone-700 stroke-[1.2]" />
        };
      case "portfolio":
        return {
          title: locale === "en" ? "Poetic Portfolio" : "Compilação Poética",
          desc: locale === "en"
            ? "Curate, structure, and publish a beautiful public presentation of your artistic research and active workspace to share with curators and the world."
            : "Cure, estruture e publique uma bela apresentação pública da sua pesquisa artística e diário de ateliê para compartilhar com curadores e com o mundo.",
          icon: <Layout className="w-8 h-8 text-stone-700 stroke-[1.2]" />
        };
      case "profile":
        return {
          title: locale === "en" ? "Artist Profile" : "Perfil do Artista",
          desc: locale === "en"
            ? "Manage your active research notebooks, review workspace statistics, edit your profile details, and control your database persistence."
            : "Gerencie seus cadernos de pesquisa ativos, revise estatísticas de ateliê, edite detalhes do seu perfil e controle sua persistência de dados.",
          icon: <User className="w-8 h-8 text-stone-700 stroke-[1.2]" />
        };
      case "settings":
        return {
          title: locale === "en" ? "Studio Settings" : "Configurações do Estúdio",
          desc: locale === "en"
            ? "Adjust workspace languages, sound effects, localized defaults, and secure storage preferences to customize your MyArtNotes experience."
            : "Ajuste idiomas, efeitos sonoros, padrões locais e preferências de armazenamento seguro para personalizar sua experiência no MyArtNotes.",
          icon: <Settings className="w-8 h-8 text-stone-700 stroke-[1.2]" />
        };
      default:
        return {
          title: locale === "en" ? "Connect Your Studio Notebook" : "Conecte Seu Caderno de Ateliê",
          desc: locale === "en"
            ? "Access a quiet, beautiful digital space to map, document, and reflect on your artistic practice without metrics, engagement traps, or social noise."
            : "Acesse um espaço digital silencioso e refinado para mapear, documentar e refletir sobre seu fazer artístico, sem métricas ou ruídos de redes sociais.",
          icon: <BookOpen className="w-8 h-8 text-stone-700 stroke-[1.2]" />
        };
    }
  };

  const { title, desc, icon } = getTabMeta();

  return (
    <div className="max-w-md mx-auto py-12 px-4 animate-fadeIn">
      <motion.div 
        className="bg-white border border-[#E6E2D5] rounded-sm p-8 shadow-xs hover:border-stone-400 transition-colors space-y-6 text-center"
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        <div className="flex flex-col items-center gap-4">
          <div className="p-3 bg-[#FCFAF7] border border-[#E6E2D5] rounded-sm">
            {icon}
          </div>
          <div className="space-y-1.5">
            <span className="text-[9px] font-mono text-stone-400 uppercase tracking-[0.2em] font-bold block">
              {locale === "en" ? "MEMBER EXCLUSIVE FEATURE" : "FUNCIONALIDADE EXCLUSIVA"}
            </span>
            <h3 className="font-serif text-xl font-light text-stone-950 tracking-wide">
              {title}
            </h3>
            <p className="text-xs text-stone-600 leading-relaxed font-serif max-w-sm mx-auto">
              {desc}
            </p>
          </div>
        </div>

        {/* Firebase Error Message with special explanation for Vercel unauthorized domain error */}
        {signInError && (
          <div className="p-4 bg-red-50/50 border border-red-200 rounded text-left text-xs font-sans text-red-800 space-y-2">
            <div className="flex items-start gap-2">
              <AlertCircle className="w-4 h-4 text-red-500 flex-shrink-0 mt-0.5" />
              <div>
                <span className="font-semibold block">
                  {locale === "en" ? "Authentication Failed" : "Falha na Autenticação"}
                </span>
                <span className="text-[11px] leading-relaxed block mt-1">{signInError}</span>
              </div>
            </div>

            {/* If Vercel auth domain issue or standard unauthorized domain, show step-by-step resolution */}
            {(signInError.toLowerCase().includes("unauthorized-domain") || 
              signInError.toLowerCase().includes("auth/unauthorized-domain")) && (
              <div className="mt-3 pt-3 border-t border-red-150 text-[11px] text-red-900 space-y-2 font-mono leading-relaxed bg-white/50 p-2.5 rounded border border-red-100">
                <p className="font-bold uppercase tracking-wider text-[9px] text-red-950">
                  {locale === "en" ? "⚙️ HOW TO FIX THIS IN FIREBASE:" : "⚙️ COMO RESOLVER ISSO NO FIREBASE:"}
                </p>
                <ol className="list-decimal list-inside space-y-1 text-[10px]">
                  <li>
                    {locale === "en" 
                      ? "Go to the Firebase Console" 
                      : "Acesse o Console do Firebase"} (console.firebase.google.com).
                  </li>
                  <li>
                    {locale === "en" 
                      ? "Select your project, then go to Authentication" 
                      : "Selecione seu projeto e vá em Authentication"}.
                  </li>
                  <li>
                    {locale === "en" 
                      ? "Click on the Settings tab, then Authorized Domains" 
                      : "Clique na aba Configurações e depois em Domínios Autorizados"}.
                  </li>
                  <li>
                    {locale === "en" 
                      ? "Click 'Add Domain' and paste your Vercel URL" 
                      : "Clique em 'Adicionar domínio' e insira a URL do seu site no Vercel"} (e.g. <span className="underline">{window.location.hostname}</span>).
                  </li>
                </ol>
                <p className="text-[9px] text-stone-500 italic mt-1 font-sans">
                  {locale === "en"
                    ? "Once added, reload your Vercel site and try signing in again!"
                    : "Após adicionar o domínio, atualize seu site no Vercel e tente o login novamente!"}
                </p>
              </div>
            )}
          </div>
        )}

        {/* Action Button */}
        <div className="pt-2">
          <button
            onClick={onSignIn}
            disabled={isSigningIn}
            className="w-full py-3 px-4 bg-stone-900 hover:bg-stone-850 text-white font-mono text-xs font-bold rounded cursor-pointer transition-all shadow-xs flex items-center justify-center gap-2.5 disabled:opacity-75"
          >
            {isSigningIn ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin text-stone-300" />
                <span>
                  {locale === "en" ? "Connecting Session..." : "Conectando Sessão..."}
                </span>
              </>
            ) : (
              <>
                <svg className="w-4 h-4 flex-shrink-0" viewBox="0 0 24 24">
                  <path
                    fill="currentColor"
                    d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
                  />
                  <path
                    fill="currentColor"
                    d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
                  />
                  <path
                    fill="currentColor"
                    d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.06H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.94l2.85-2.22.81-.63z"
                  />
                  <path
                    fill="currentColor"
                    d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.06l3.66 2.84c.87-2.6 3.3-4.52 6.16-4.52z"
                  />
                </svg>
                <span>
                  {locale === "en" ? "Enter with Google" : "Acessar com o Google"}
                </span>
              </>
            )}
          </button>
        </div>

        <div className="text-[10px] text-stone-500 font-sans">
          {locale === "en"
            ? "Requires a free Google account to secure your private studio notes."
            : "Requer uma conta do Google para proteger suas anotações privadas."}
        </div>
      </motion.div>
    </div>
  );
}
